import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        ><nav>
          <h3 id="logo">Saim Khan</h3>
        <ul>
        
      <li><Link href="/">Home</Link></li>
      <li><Link href="/About-me">About </Link></li>
      <li><Link href="/Resume">Resume </Link></li>
      <li><Link href="/Contact">Contact</Link></li>
      <li><Link href="/Project">Project</Link></li>
    </ul></nav>
      
        {children}
        
          
        
      </body>
      
    </html>
  );
}
